Parameters:

  Domain:
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    Description: The domain name you would like to create a HostedZone for
    ConstraintDescription: Must be a valid domain

Resources:

  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref Domain
