Parameters:

  HostedZoneId:
    Type: String
    AllowedPattern: '[A-Z0-9]{14}'
    Description: Existing HostedZone's ID
    ConstraintDescription: Must be an AWS Route53 HostedZoneId

  SiteDomainName:
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    Description: Domain name for site e.g. rupertbg.nz (no www)
    ConstraintDescription: Must be a valid domain name

  WebsiteBucket:
    Type: String

  WebsiteBucketDomainName:
    Type: String

Resources:

  AcmCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref SiteDomainName
      SubjectAlternativeNames:
        - !Sub www.${SiteDomainName}
      ValidationMethod: DNS

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
        - Sid: CloudFrontAccess
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CloudFrontIdentity.S3CanonicalUserId
          Action: s3:GetObject
          Resource: !Sub arn:aws:s3:::${WebsiteBucket}/*

  CloudFrontIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub Identity for ${SiteDomainName}

  CloudfrontDistro:
    Type: AWS::CloudFront::Distribution
    DependsOn:
      - CloudFrontIdentity
    Properties:
      DistributionConfig:
        Comment: Cloudfront Distribution pointing to S3 bucket
        Origins:
        - DomainName: !Ref WebsiteBucketDomainName
          Id: S3Origin
          S3OriginConfig:
            OriginAccessIdentity: !Sub origin-access-identity/cloudfront/${CloudFrontIdentity}
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        Aliases:
          - !Ref SiteDomainName
          - !Sub www.${SiteDomainName}
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          Compress: true
          DefaultTTL: 0
          MaxTTL: 0
          MinTTL: 0
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: true
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificate
          SslSupportMethod: sni-only

  WebsiteDNSName:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
        - Name: !Sub ${SiteDomainName}.
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistro.DomainName
        - Name: !Sub www.${SiteDomainName}.
          Type: A
          AliasTarget:
            HostedZoneId: Z2FDTNDATAQYW2
            DNSName: !GetAtt CloudfrontDistro.DomainName
